### ISSUE TITLE
BITS on windows 10

### ISSUE THREAD

**Issue by mgreen27** [ANSSI-FR/bits_parser#4]
Hello,

Nice tool. I notice the BITS/QMGR files are different on my Win10 machine. I was wondering if you have done any work or seen any research on parsing Windows 10 BITS?

Matt

**Comment by mc-anssi** [comment]
Hi Matt,
The format of QMGR files has changed with latest Windows 10.
MS has migrated from an undocumented format to an ESE database (as for lots of MS products, such as exchange, IE Webcache, etc).
Bits_parser parser works with the previous QMGR queue files.
There are a lots of tools and research to carve ESE databases.
Morgane
